### ISSUE TITLE
Explore automatic nonce in tags

### ISSUE THREAD

**Issue by Bennyoak** [SpiderOak/django-csp-nonce#10]
As part of a feature request, it was suggested that DCN support auto-noncing in tags; where DCN would handle injecting the nonce into `<script>/<style>` tags.

I've come up with a way that this could _possibly_ work, without using re or third-party dependencies. So I may add it as an experimental extension in future versions.

The main issues I see are that parsing html can be fairly expensive, especially once it's processing every request. Plus I'm not sure (from a security perspective) what kind of leaks or errors could bubble up as a result.

This is an open discussion. Feel free to add your 2 cents.

**Comment by adamchainz** [comment]
This is a bad idea as script or style tags in a rendered html template may come from user-provided data and thus you'd be obviating what csp strict-dynamic protects against. Btw thanks for the package, I came here looking after it was mentioned on the django-developers mailing list about adding CSP nonces to django core: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/django-developers/n--RWhLAoYM/m06qUOFnAgAJ

**Comment by Bennyoak** [comment]
Hi @adamchainz - glad you found the package useful. My apologies for the late reply. New job has kept me busy. But now that things are calming down, I'm looking forward to giving DCN some much needed attention.

In response to your comment, I agree that auto-noncing may not be the most secure approach. And I certainly wouldn't want to offer an option that makes a site _less_ secure as a result of using DCN. Given there's a ton of updates that need to happen first, features and ease-of-use options will have to happen down the road, anyway.

**Comment by Bennyoak** [comment]
Closing this as it will likely cause more problems than fix.
