### ISSUE TITLE
Nacl

### ISSUE THREAD

**Issue by kravietz** [SpiderOak/django-csp-nonce#11]
Using `nacl` just to produce a 24 byte nonce seems to be a bit of an overkill. `os.urandom(24)` would be perfectly sufficient in this case and it might be much shorter as well as this is not really a cryptographic usage - 24 bytes is 192 bits of entropy and for CSP usage something like 8-16 bytes (64-128 bits) would be sufficient too. In Python 3.6 there's even more suitable [secrets](https://docs.python.org/3/library/secrets.html) module that could be used instead of `os.urandom`.

**Comment by Bennyoak** [comment]
Good point. I have plans to make nacl an opt-in mech in the near future.

**Comment by Bennyoak** [comment]
Closing this issue. DCN is now pip installable at v1.0.0 (out of beta)
PyNacl has been replaced by `os.urandom()`
