### ISSUE TITLE
Feature Request: Option to disable nonce when django-csp policy modification decorators are used

### ISSUE THREAD

**Issue by nkgilley** [SpiderOak/django-csp-nonce#19]
Is it possible to have the nonce disabled when a django-csp decorator such as `@csp_update` is used on a view?

**Comment by Bennyoak** [comment]
Hi @nkgilley - I believe django-csp now supports (or will soon support) nonce. I haven't yet tested how this interacts with django-csp-nonce. That is, it's entirely possible that having both would create a conflict. As such, I don't have a plan for further support of django-csp.

With that said, the closest decorator-spectifice support DCN provides is more in the way of a side effect regarding `@csp_exempt`; where no nonce is generated if a CSP header is not detected. If your goal is to remove them based on certain decorators or other criteria, you'll have to build a sieve that does so.

Feel free to reach out if you have any more questions.
