### ISSUE TITLE
[Feature Request] Support automatic noncing and 'strict-dynamic'

### ISSUE THREAD

**Issue by mikispag** [SpiderOak/django-csp-nonce#8]
It would be really cool if you could add support for `'strict-dynamic'` ([W3C](https://w3c.github.io/webappsec-csp/#strict-dynamic-usage)) and automatic noncing (no need to modify the templates to insert nonces in `<script>` tags).

Google is offering [Google Patch Rewards](https://csp.withgoogle.com/docs/faq.html#csp-patches) for integrating CSP in popular frameworks and facilitating adoption (as you already did, so please apply!). 

The most recent research on CSP demonstrated that [the whitelist-based approach is intrinsically flawed for XSS mitigation](https://research.google.com/pubs/pub45542.html), and that [a nonce/hash + 'strict-dynamic' policy](https://csp.withgoogle.com/docs/strict-csp.html), similar to the ones already served by important Google products, is in the quasi-totality of cases the only working solution.

There are a lot of misconceptions about CSP, and getting rid of things that are proven not to work is good - the worst thing you can have is a false sense of security.

If you could also add a link to the [CSP Evaluator](https://csp-evaluator.withgoogle.com/) to your README, to let users evaluate the quality of their policy, it would be awesome.

Please do not hesitate to get back to me if you need any additional information or have doubts.

## More resources

- https://csp.withgoogle.com
- https://csp.withgoogle.com/docs/strict-csp.html
- https://csp-evaluator.withgoogle.com
- https://www.google.com/about/appsecurity/patch-rewards/

**Comment by Bennyoak** [comment]
Hi there @mikispag 

Thanks for your input!
We do plan to support `'strict-dynamic'` in upcoming releases, and the possibility of automatic tag insertion is on the table for discussion.

@nico3333fr has an exhaustive and... _useful_ list of CSP bits at https://github.com/nico3333fr/CSP-useful. You should drop him a line with the above resources. At a glance, it looks like you have a couple here that he doesn't have yet.

Cheers!

**Comment by nico3333fr** [comment]
Thanks @Bennyoak for pointing it out, I've added these resources to my CSP repo ;)

**Comment by Bennyoak** [comment]
@mikispag - Just wanted to let you know that strict-dynamic support is on deck. It should be available within the week.

Cheers!

**Comment by mikispag** [comment]
Thanks a bunch, keeping an eye on this.

**Comment by Bennyoak** [comment]
`strict-dynamic` support is now available in 1.0b20 via the repo and pip
